name: Update Docker Hub Description

on:
  push:
    branches:
      - develop
    paths:
      - "README.md"
      - ".github/workflows/dockerhub-description.yml"
  workflow_dispatch:

jobs:
  dockerhub-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: fanss/music-tagger
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./README.md
